#!/usr/bin/env python

"""
Credit: Improvised through https://github.com/byjokese/Generate-Index-Files/blob/master/generate-index.py

Recursively generate index.md if not exist
Usage: ./gen_index_md.py
"""

import os
from pathlib import Path

# Set This to True if you don't want index.md to be generated for subdirectory with only a single <content>.md page and no subdirectory within
collapse_single_pages = True
# Set This to True if you don't wnat index.md to be generated for subdirectory that has no <content>.md pages and only subdirectories within
skip_intermediate_sections = True

indexBodyTemplate = """<!--- AUTOGENERATED --->
# {section}

## Sections of {section}

"""

def index_folder(folderPath: Path):
	indexBody = indexBodyTemplate.format(section= os.path.basename(os.path.normpath(folderPath))  )
	
	numContentMDFile = 0
	numSubFolder = 0

	for file in os.listdir(folderPath):
		#Avoiding index.md files
		if ".md" in file and file != 'index.md':
			numContentMDFile += 1
			indexBody += "- [[" + file.replace(".md", "") + "]]" +  "\n"
		if os.path.isdir(folderPath / file):
			numSubFolder += 1
			indexBody += "- [[" + file.replace(".md", "") + "]]" +  "\n"
			#Recursive call to continue indexing
			index_folder(folderPath / file)

	
	if collapse_single_pages and numContentMDFile == 1 and numSubFolder == 0:
		return
	elif skip_intermediate_sections and numContentMDFile == 0 and numSubFolder > 0:
		return
	else:
		# Write index.md file if not exist, or update if auto-generated before
		if not os.path.isfile(folderPath / 'index.md'):
			print("Auto-generating missing index in:" + str(folderPath))
			index = open(folderPath / 'index.md', "w")
			index.write(indexBody)
			index.close()
		else:
			index = open(folderPath / 'index.md', "r+", encoding="utf-8")
			if index.readline().strip() == "<!--- AUTOGENERATED --->":
				print("Overriding Auto-generated index in:" + str(folderPath))
				index.seek(0)
				index.write(indexBody)
				index.truncate()
			index.close()


index_folder(Path.cwd()/"docs")