site_name: Oscar's Personal Handbook

theme:
    name: 'material'
    palette:
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

# 1. Automatic index.md in section, refer to mkdocs-section-index,
# 2. Extended nav syntax from mkdocs-literate-nav, Refer to
# https://oprypin.github.io/mkdocs-literate-nav/reference.html#mkdocs-native-nav
nav:
- devops:
  - platform engineering: 'devops/platform engineering/'
  - networking: devops/networking/
  - jenkins: devops/jenkins/
  - terraform: devops/terraform/

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  - toc:
      permalink: true

plugins:
  - search
  - roamlinks
  - literate-nav
  - section-index
  - mermaid2

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
